version: '3.8'
services:
alyssium:
build: .
image: alyssium-core\:latest
container\_name: alyssium-core
restart: unless-stopped
env\_file:
\- .env
ports:
\- "8000:5000"         # Host 8000 -> Container 5000 (Flask default)
volumes:
\- .:/app               # Mount project code for live reload (dev)
\- logs\:/app/logs       # Persist logs
healthcheck:
test: \["CMD-SHELL", "python -c 'import socket; sock=socket.create\_connection(("localhost", 5000), 1); sock.close()' || exit 1"]
interval: 30s
timeout: 5s
retries: 3

volumes:
logs:
driver: local
